### ISSUE TITLE
Is this compatible with Xcode 9.2?

### ISSUE THREAD

**Issue by wittyapps** [anlgrses/Dji-RTMP-Client#1]
Hello,

I am trying to import this project into Xcode 9.2 and am having a little trouble getting it to build.  Any suggestions?

**Comment by anilgurses** [comment]
Hi,
Sorry for the late reply.  It could be built on Xcode 9.2. You should be aware of the library versions. There has been a long time not maintaining this project. Please let me know if the issue not caused by lib versions.
